import { HorizontalBox, VerticalBox,  LineEdit, Button, TextEdit, ListView, CheckBox, Palette } from "std-widgets.slint";

import { Style, View, TabType, ViewInfo, RecordRes } from "../common.slint";

import { Calendar, CalendarStatus } from "../components/calendar.slint";
import { AutoPopupWindow } from "../components/popupwindow.slint";
import { GeneralButton } from "../components/buttons.slint";

import { ReviewStatus, ReviewController } from "review-manager.slint";
import { RecordStatus, RecordController } from "record-manager.slint";
import { ListController } from "list-manager.slint";
import { GlobalManager } from "global-manager.slint";

component Record {
    in property <[ViewInfo]> page-items;

    VerticalBox {
        height: 100%;

        Calendar {
            height: 14%;
        }

        Rectangle {
            height: 61.8%;
            background: Style.details-background-color;

            record-content := TextEdit {
                font-size: 2.5rem;
                width: 100%;
                height: 100%;
                opacity: 0.618;
                horizontal-alignment: left;
                placeholder-text: "enter your text...";

                function unfocus() {
                    self.clear-focus();
                }

                function clear-content() {
                    self.select-all();
                    self.clear-selection();
                }

                key-released(event) => {
                    if event.modifiers.control && event.text == Key.Return {
                        save-button.save();
                        return accept;
                    }
                    return accept;
                }
            }

            save-warnning := AutoPopupWindow {
                after-auto-close => {
                    record-content.unfocus();
                }

                Rectangle {
                    x: parent.width * 38.2%;
                    y: parent.height * 38.2%;
                    height: parent.height * 23.6%;
                    width: parent.width * 23.6%;
                    opacity: 0.8;
                    background: Style.popup-win-background;
                    border-radius: self.height * 14.6%;
                    Text {
                        text: save-button.recordd-res.msg;
                        font-size: parent.height * 14.6%;
                        font-family: Style.default-font-family;
                    }
                }
            }
        }

        save-button := HorizontalBox {
            in-out property <RecordRes> recordd-res;

            height: 6.18%;
            alignment: center;

            GeneralButton {
                width: 10rem;
                button-name: "save";
                button-font-size: 1.5rem;

                click-button => {
                    save-button.save();
                }
            }

            function save() {
                record-content.focus();
                save-button.recordd-res = RecordController.save-records(record-content.text, CalendarStatus.date);
                if save-button.recordd-res.success {
                    GlobalManager.refresh();
                    record-content.clear-content();
                }
                save-warnning.popup-and-hide();
            }
        }
    }
}

export { Record, RecordRes }
