import { Style } from "../common.slint";

component GeneralButton inherits Rectangle {
    in property <string> button-name;
    in property <relative-font-size> button-font-size;

    callback click-button();

    background: Style.save-button-color;
    border-width: 0.1rem;
    border-color: Style.save-button-border-color;
    border-radius: min(self.height / 1.618, 36px);

    Text {
        text: button-name;
        font-size: parent.button-font-size;
        font-family: Style.default-font-family;
        horizontal-alignment: center;
        vertical-alignment: center;
        color: Style.save-button-font-color;
        TouchArea {
            clicked => {
                root.click-button();
            }
        }
    }
}

component IconButton inherits Rectangle {
    in property <image> icon-url;
    in property <brush> icon-color: Style.icon-shadow-color;
    in property <brush> icon-shadow-color: Style.icon-shadow-color;

    border-radius: min(self.height / 1.618, 36px);
    drop-shadow-blur: t.has-hover ? self.height / 1.618 / 1.618 : 0;

    callback click-button();
    callback hover-action();

    t := TouchArea {
        width: 100%;
        height: 100%;
        clicked => {
            root.click-button();
        }
        changed has-hover => {
            root.hover-action();
        }
        Image {
            width: 61.8%;
            height: 61.8%;
            source: icon-url;
            image-fit: contain;
            colorize <=> icon-color;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }

    states [
        show-border when t.has-hover: {
            drop-shadow-color: icon-shadow-color;
        }
    ]

    animate drop-shadow-color {
        duration: 618ms;
        easing: ease-out;
    }
}

export { GeneralButton, IconButton }
