import { HorizontalBox, Palette } from "std-widgets.slint";
import { Style } from "../common.slint";

struct Task {
    id: int,
    content: string,
    create-date: string,
    finished: bool,
}

global RichCheckBoxController { }

global RichCheckBoxStatus { }

component RichCheckBox inherits HorizontalLayout {
    in property <Task> task;
    in property <int> idx;
    in-out property <bool> finished: task.finished;

    callback on-checked();
    callback on-select();
    callback on-double-select();
    callback on-del();
    callback on-swipe-to-left();
    callback on-swipe-to-right();

    alignment: space-around;

    // checked
    check-box := Rectangle {
        width: parent.height * 52.8%;
        height: parent.height * 52.8%;
        border-width: 1px;
        border-color: #CCC;
        border-radius: 8px;
        background: finished ? #4CAF50 : #CCC;

        // Display checkmark if finished
        Text {
            text: finished ? "✔" : "";
            font-size: parent.height / 1.618;
            color: #56640E;
            font-family: Style.default-font-family;
            vertical-alignment: center;
        }

        TouchArea {
            clicked => {
                root.on-checked();
            }
        }

        animate background {
            duration: 318ms;
            easing: ease-in-out;
        }
    }

    // content
    Rectangle {
        height: parent.height * 52.8%;
        width: (parent.width - check-box.width - del-button.width) * 95%;
        cache-rendering-hint: true;
        Text {
            width: parent.width;
            height: parent.height;
            horizontal-alignment: left;
            vertical-alignment: center;
            text: root.task.content;
            color: #56640E;
            font-size: parent.height / 1.618;
            font-family: Style.default-font-family;
            overflow: elide;
            cache-rendering-hint: true;
        }

        TouchArea {
            height: parent.height;
            width: parent.width;

            clicked => {
                root.on-select();
            }
            double-clicked => {
                root.on-double-select();
            }
            moved => {
                if (self.enabled && self.pressed) {
                    if self.mouse-x - self.pressed-x < -parent.width * 9% {
                        root.on-swipe-to-left();
                    } else if self.mouse-x - self.pressed-x > parent.width * 9% {
                        root.on-swipe-to-right();
                    }
                }
            }
        }
    }

    del := TouchArea {
        width: parent.height * 61.8%;
        height: parent.height * 61.8%;

        clicked => {
            root.on-del();
        }

        del-button := Rectangle {
            x: parent.has-hover ? 1px : 0px;
            width: parent.height * 52.8%;
            height: parent.height * 52.8%;
            opacity: parent.has-hover ? 0.619 : 0;
            border-width: 1px;
            border-color: #CCC;
            border-radius: 8px;
            drop-shadow-color: #CCC;
            drop-shadow-blur: 4px;

            Text {
                text: "X";
                font-size: parent.height / 1.618;
                font-family: Style.default-font-family;
                color: #56640E;
                vertical-alignment: center;
            }

            animate drop-shadow-color, opacity, x {
                duration: 618ms;
                easing: ease-out-circ;
            }
        }
    }
}

export { RichCheckBox, RichCheckBoxController, RichCheckBoxStatus, Task }
