import { HorizontalBox, VerticalBox,  LineEdit, Button, TextEdit, ListView, CheckBox, Palette } from "std-widgets.slint";

import { Style, View, TabType, ViewInfo } from "common.slint";
import { NavBar, NavItem, Calendar } from "nav.slint";
import { Record } from "pages/record.slint";
import { Review } from "pages/review.slint";
import { List } from "pages/list.slint";


export { Task, Record } from "common.slint";

export { RecordController, RecordStatus } from "pages/record-manager.slint";
export { ReviewController, ReviewStatus } from "pages/review-manager.slint";
export { ListController, ListStatus } from "pages/list-manager.slint";

export { CalendarController } from "components/calendar.slint";
export { RichCheckBoxController } from "components/checkbox.slint";

export component MainWindow inherits Window {
    in-out property <string> name;
    title: "MemToy";
    min-width: 648px;
    min-height: 400px;
    preferred-height: 900px;
    preferred-width: 1254px;
    background: Style.surface;

    VerticalBox {
        nav := NavBar {
            min-height: 36px;
            width: 100%;
            nav-items: View.view-info;
        }

        if nav.active-tab-type == TabType.record: record := Record {
            min-height: root.height * 80%;
            page-items: View.view-info;
        }

        if nav.active-tab-type == TabType.review: Review {
            min-height: root.height * 80%;
            page-items: View.view-info;
        }

        if nav.active-tab-type == TabType.list: List {
            min-height: root.height * 80%;
            page-items: View.view-info;
        }
    }

    forward-focus: global-key-handler;
    global-key-handler := FocusScope {
        key-pressed(event) => {
            // switch tab
            // on mac, slint maps cmd to control, control to meta, which is subtle.
            if (event.modifiers.control || event.modifiers.meta) && event.text == Key.Tab {
                nav.switch-next-tab();
            }
            accept
        }
    }
}
