export global Style {
    out property <length> nav-bar-height: 64px;
    out property <length> nav-bar-min-len: 300px;
    out property <color> nav-activate-background: #C6A368;
    out property <color> nav-border-color: #C6A368;
    out property <color> nav-item-font-color: #6D5033;
    out property <color> surface: #120F0A;

    out property <length> min-border: 36px;

    out property <length> calendar-font-size: nav-bar-height;
    out property <length> calendar-height: nav-bar-height * 1.618 * 1.618;

    out property <color> calendar-font-color: #6D5033;
    out property <color> popup-win-background: #695F4A;
    out property <color> popup-win-font-color: #C6A368;

    out property <duration> animation-default-duration: 318ms;

    out property <length> record-save-height: 36px;
    out property <length> record-save-widdth: record-save-height * 1.618;

    out property <color> review-task-font-color: #6D5033;
    out property <color> review-del-warn-font-color: #3B392F;

    out property <color> save-button-color: #C6A368;
    out property <color> save-button-font-color: #6D5033;

    out property <color> details-background-color: #C6A368;

    out property <string> default-font-family: "Comic Sans MS";

    out property <color> icon-shadow-color: #C6A368;
}

enum TabType { record, review, list }

enum PageType { record-page, review-page, list-page }

struct ViewInfo {
    nav-bar-name: string,
    tab-type: TabType,
    page-type: PageType,
}

export global View {
    in property <[ViewInfo]> view-info: [
        { nav-bar-name: "Record", tab-type: TabType.record, page-type: PageType.record-page },
        { nav-bar-name: "Review", tab-type: TabType.review, page-type: PageType.review-page },
        { nav-bar-name: "List", tab-type: TabType.list, page-type: PageType.list-page },
    ];
}

struct RecordRes {
        success: bool,
        msg: string,
}

export { TabType, PageType, ViewInfo, RecordRes }
