import { HorizontalBox, VerticalBox,  LineEdit, Button, TextEdit, ListView, CheckBox, Palette, StandardButton, ScrollView } from "std-widgets.slint";

import { Style, View, TabType,  ViewInfo } from "common.slint";

import { RichCheckBox, RichCheckBoxController, Task, RichCheckBoxStatus } from "components/checkbox.slint";
import { AutoPopupWindow } from "components/popupwindow.slint";

global ReviewController {
    pure callback review-today() -> [Task];
    callback toggle-task(id: int, finished: bool);
    callback del-task(id: int);

    public function refresh() {
        ReviewStatus.tasks = ReviewController.review-today();
    }
}

global ReviewStatus {
    in property <[Task]> tasks: ReviewController.review-today();
    in property <Task> selected-task;
    in property <Task> deleted-task;
}

component Review inherits VerticalLayout {
    in property <[ViewInfo]> page-items;

    Rectangle {
        ListView {
            for task[idx] in ReviewStatus.tasks: VerticalLayout {
                height: 14%;
                width: parent.width * 98.382%;

                content := RichCheckBox {
                    task: task;
                    idx: idx;
                    height: parent.height * 90%;

                    on-checked => {
                        self.finished = !self.finished; // Toggle the finished state
                            ReviewStatus.tasks[idx].finished = self.finished;
                        ReviewController.toggle-task(task.id, self.finished);
                    }
                    on-select => {

                        ReviewStatus.selected-task = task;
                    }
                    on-double-select => {
                        ReviewStatus.selected-task = task;
                        details.copy-content();
                        copied-warnning.popup-and-hide()
                    }
                    on-del => {
                        ReviewStatus.deleted-task = self.task;
                        del-warning.show();
                    }
                    on-swipe-to-left => {
                        RichCheckBoxStatus.del-button-enabled = true;
                        RichCheckBoxStatus.del-button-x-position = 0;
                    }
                    on-swipe-to-right => {
                        RichCheckBoxStatus.del-button-enabled = false;
                        RichCheckBoxStatus.del-button-x-position = root.width;
                    }
                }
            }
        }

        copied-warnning := AutoPopupWindow {
            Rectangle {
                x: parent.width * 38.2%;
                y: parent.height * 38.2%;
                height: parent.height * 23.6%;
                width: parent.width * 23.6%;
                background: Style.tab-font-color;
                border-radius: self.height * 14.6%;
                opacity: 0.8;
                Text {
                    text: "Copy to Clipboard";
                    font-size: parent.height * 14.6%;
                    font-family: "Comic Sans MS";
                }
            }
        }

        del-warning := PopupWindow {
            x: parent.width * 26.4%;
            y: parent.height * 26.4%;
            height: root.height * 47.2%;
            width: root.width * 47.2%;

            Rectangle {
                height: 100%;
                width: 100%;
                background: Style.tab-font-color;
                border-radius: self.height * 14.6%;
                opacity: 0.8;

                VerticalBox {
                    height: parent.height;
                    width: parent.width;
                    alignment: space-between;

                    Rectangle {
                        height: parent.height * 14.6%;
                        Text {
                            horizontal-alignment: center;
                            vertical-alignment: top;
                            text: "Delete the task?";
                            font-size: parent.height / 1.618;
                            font-family: "Comic Sans MS";
                            font-weight: 800;
                        }
                    }

                    ScrollView {
                        width: parent.width;
                        height: parent.height * 52.8%;
                        viewport-height: t.height;
                        t := Text {
                            horizontal-alignment: center;
                            width: parent.width * 90%;
                            text: ReviewStatus.deleted-task.content;
                            wrap: word-wrap;
                            font-size: parent.height * 14.6%;
                            font-family: "Comic Sans MS";
                        }
                    }

                    HorizontalBox {
                        alignment: space-around;
                        height: parent.height * 14.6%;
                        width: parent.width;

                        TouchArea {
                            height: parent.height * 52.8%;
                            width: parent.width * 33%;
                            clicked => {
                                debug("[slint] delete task id: " + ReviewStatus.deleted-task.id);
                                ReviewController.del-task(ReviewStatus.deleted-task.id);
                                ReviewController.refresh();
                            }
                            Rectangle {
                                height: parent.height;
                                width: parent.width;
                                border-radius: self.height * 14.6%;
                                background: white;
                                Text {
                                    text: "yes";
                                    font-size: parent.height * 44.7%;
                                    horizontal-alignment: center;
                                    vertical-alignment: center;
                                    color: Style.tab-font-color;
                                }
                            }
                        }

                        StandardButton {
                            kind: no;
                            height: parent.height;
                            clicked => {
                                del-warning.close();
                            }
                        }
                    }
                }
            }
        }
    }

    details := Rectangle {
        height: parent.min-height * 22.4%;

        border-radius: 4px;
        padding: 4px;
        background: Style.details-background-color;
        opacity: 0.618;

        TouchArea {
            mouse-cursor: copy;

            clicked => {
                details.copy-content();
                copied-warnning.popup-and-hide();
            }

            details-content := TextEdit {
                text: ReviewStatus.selected-task.content;
                font-size: self.height * 14.4%;
                width: 100%;
                height: 100%;
                opacity: 0.618;
                horizontal-alignment: left;
                enabled: false;
                wrap: word-wrap;
            }
        }

        animate opacity { duration: 236ms; }

        function copy-content() {
            details-content.select-all();
            details-content.copy();
            details-content.set-selection-offsets(0, 0);
        }
    }
}

export { Review, ReviewController, ReviewStatus, Task }
