name: Rust

on:
  create:
    tags:
      - '**'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  bundle-mac:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-13-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo-packager
        run: cargo install cargo-packager
      - name: Bundle packages
        run: cargo packager --formats dmg
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./bundle/MemToy_*.dmg
          # body_path: CHANGELOG.md
          draft: false
          prerelease: false
