name: Rust

on:
  create:
    tags:
      - '**'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  bundle-mac:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ steps.rust-toolchain.outputs.cachekey }}
      # https://github.com/marketplace/actions/rustup-toolchain-install
      - name: Rust Toolchain
        id: rust-toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install cargo-packager
        run: cargo install cargo-packager
      - name: Bundle packages
        run: cargo packager --formats dmg
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            ./bundle/MemToy_*.dmg
          # body_path: CHANGELOG.md
          draft: false
          prerelease: false
