name: Rust

on:
  create:
    tags:
      - '**'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  bundle-mac:
    runs-on: macos-latest
    outputs:
      sha256: ${{ steps.get_sha256.outputs.sha256 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # https://github.com/marketplace/actions/rustup-toolchain-install
      - name: Rust Toolchain
        id: rust-toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install cargo-packager if not installed
        id: install_cargo_packager
        run: |
          if command -v cargo-packager &> /dev/null; then
            cargo packager --version
          else
            cargo install cargo-packager && cargo packager --version
          fi

      - name: Build package for mac
        run: cargo packager --formats dmg

      - name: Get sha256
        id: get_sha256
        run: |
          DMG_FILE=$(find ./bundle -name "MemToy_*.dmg" -print -quit)
          SHA256=$(shasum -a 256 $DMG_FILE | awk '{print $1}')
          echo "sha256=$SHA256" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            ./bundle/MemToy_*.dmg
          # body_path: CHANGELOG.md
          draft: false
          prerelease: false

  update-homebrew-tap:
    needs: bundle-mac
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew-tap
        uses: actions/checkout@v4
        with:
          repository: Rianico/homebrew-tap
          token: ${{ secrets.HOMEBREW_TAP_PAT }}
          ref: main

      - name: Update Cask
        run: |
          set -e
          VERSION=$(echo ${{ github.ref_name }} | sed 's/v//')
          SHA256="${{ needs.bundle-mac.outputs.sha256 }}"
          CASK_FILE="Casks/memtoy.rb"

          echo "Updating Cask file: $CASK_FILE"
          echo "Version: $VERSION"
          echo "SHA256: $SHA256"

          sed -i "s/^  version ".*"/  version \"$VERSION\"/" "$CASK_FILE"
          sed -i "s/^  sha256 ".*"/  sha256 \"$SHA256\"/" "$CASK_FILE"

          echo "Cask file updated:"
          curl -H "Authorization: token ${{ secrets.HOMEBREW_TAP_PAT }}" https://api.github.com/repos/Rianico/homebrew-tap
          cat "$CASK_FILE"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Casks/memtoy.rb
          git commit -m "Update memtoy cask to $VERSION"
          git push
