name: Rust

on:
  create:
    tags:
      - '**'
      
env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  CARGO_TERM_COLOR: always
  PACKAGE_NAME: $(echo MemToy_${{ github.ref_name }}_arm64

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build the project
        run: cargo build --release --verbose
      - name: Package the binary
        run: |
          mkdir -p release
          cp target/release/MemToy release/
          tar -czvf release/$PACKAGE_NAME.tar.gz -C release MemToy
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./release/$PACKAGE_NAME.tar.gz
          # body_path: CHANGELOG.md
          draft: false
          prerelease: false
