name: Rust

on:
  create:
    tags:
      - '**'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  bundle-mac:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # https://github.com/marketplace/actions/rustup-toolchain-install
      - name: Rust Toolchain
        id: rust-toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install cargo-packager if not installed
        id: install_cargo_packager
        run: |
          if command -v cargo-packager &> /dev/null; then
            cargo packager --version
          else
            cargo install cargo-packager && cargo packager --version
          fi

      - name: Build package for mac
        run: cargo packager --formats dmg

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            ./bundle/MemToy_*.dmg
          # body_path: CHANGELOG.md
          draft: false
          prerelease: false
